# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Everyday Task

on:
  push:
    branches: ['main']
  schedule:
#   这一行是每天
    #     - cron: '50 15 * * *'
#     这一行是每周
    - cron: '10 23 ? * 3'
env:
  hahaha: 哈哈哈
  COOKIE: ${{ secrets.COOKIE }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - run: npm i
      - run: echo "$COOKIE $hahaha"
      - run: npm run task "$COOKIE"

      - name: Commit
        if: success()
        run: |
          git config --global user.email 862670198@qq.com
          git config --global user.name vannvan
          git add .
          git commit -m "`date`"
          # git pull --rebase

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
  # update-readme:
  #   name: GitHub README Generator
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: th3c0d3br34ker/github-readme-info@master
  #       with:
  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         TIMEZONE: 'Asia/Kolkata'
  #         SHOW_LINES_OF_CODE: 'True'
  #         SHOW_PROFILE_VIEWS: 'True'
  #         SHOW_DAILY_COMMIT: 'True'
  #         SHOW_WEEKLY_COMMIT: 'True'
  #         SHOW_LANGUAGE: 'True'
  #         SHOW_TOTAL_CONTRIBUTIONS: 'True'
